name: Bump Version and Publish

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # or whatever version you prefer
          registry-url: 'https://registry.npmjs.org'

      - name: Install release-please
        run: npm install -g release-please

      - name: Determine next version and update package.json
        run: |
          # Determine next version
          output=$(release-please manifest-pr --dry-run --token=${{ secrets.GITHUB_TOKEN }} --repo-url=${{ github.repository }} --default-branch=main)
          next_version=$(echo "$output" | grep -oP 'release-please-[0-9.]+' | sed 's/release-please-//')
          echo "Next version: $next_version"

          # Count existing pre-releases
          count=$(npm view . versions --json | jq "[.[] | select(startswith(\"$next_version-next.\"))] | length")
          echo "Number of existing pre-releases: $count"

          # Create final version string
          final_version="${next_version}-next.${count}"
          echo "Final version: $final_version"

          # Update package.json
          npm version $final_version --no-git-tag-version
          npm publish --preid=next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
