name: Publish TSDoc to GitHub Pages

permissions:
  contents: write
  actions: read
  checks: write
  deployments: write
  issues: write
  metadata: read
  packages: read
  pull-requests: write
  statuses: write

on:
  push:
    branches:
      - main
      - docs

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Generate documentation
        run: npx typedoc

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
